Added pot_vortic module
MeteoSwiss-APN/icon_data_processing_incubator pull request #49
Opened 2023-04-26 07:04 UTC by cfkanesan

I tried to rebase the original branch but the history was too convoluted and I was afraid of introducing new bugs in the conflict resolution so I had to resort to copying the files over. I also made an attempt at using pytest fixtures to manage the fieldextra run to unload the test body a bit. Let me know what you think.

The tests are currently failing but you can already have a look and comment where relevant.

2023-04-26 07:15 UTC, cfkanesan commented on src/idpi/constants.py
This was present in Thierry's branch but it seems that the main has diverged from this approach. Should I drop it?

2023-04-26 07:15 UTC, cfkanesan commented on src/idpi/operators/curl.py
> +}
I modified the handling of the stencils to be more static and less dependent on the mutation of the global state. That can be a pain to work with in a concurrent execution context.

2023-04-26 07:15 UTC, cfkanesan commented on src/idpi/operators/curl.py
> +class FDField:
The purpose of this class is to wrap the dataarray and provide syntaxic sugar for the expressions below.

2023-04-26 07:15 UTC, cfkanesan commented on src/idpi/operators/curl.py
> +    tgrlat: xr.DataArray = np.tan(lat * deg2rad)  # type: ignore[assignment]
One of the issues in the original branch is that the lattitude values are in degrees and not micro degrees.

2023-04-26 07:15 UTC, cfkanesan commented on src/idpi/operators/pot_vortic.py
> +    inv_dlat = 1 / (dlat * deg2rad)
The confusion on the units was present here too

2023-04-26 07:15 UTC, cfkanesan commented on src/idpi/operators/pot_vortic.py
> +    )
I'm not the biggest fan of this but at least it doesn't mutate the input variables. I still need to confirm that this works.

2023-04-26 07:15 UTC, cfkanesan commented on tests/test_idpi/test_potvortic.py
> +    print(pv_ref.data)
leftovers to remove

2023-04-26 07:15 UTC, cfkanesan commented on tests/test_idpi/test_potvortic.py
> +def fieldextra_executable(fieldextra_executable):
Here is an example of the fixture being overridden at the module level.

[] remove this before merging

2023-05-02 21:35 UTC, cosunae requested changes

2023-05-02 21:35 UTC, cosunae commented on src/idpi/operators/curl.py
> +    du_dphi = ((u["cpc"] + u["mpc"]) - (u["cmc"] + u["mmc"])) * 0.25 * inv_dlat
I am not very convinced about the usage of this custom syntax. Also notice that sometimes we use it as u["cmc"]  while below we also use u("cmc"). 

I will suggest looking into more standard syntax or aligned with other projects.
* variant 1: 
```u[0,1,0]``` equals the syntax used here as ```u["cpc"]```
it is used also in numba:
https://numba.pydata.org/numba-doc/latest/user/stencil.html
and in gt4py (cartesian mode)
https://github.com/GridTools/gt4py/blob/main/examples/cartesian/demo_horizontal_diffusion.ipynb
* variant 2:
Use a shift operator (concept of gt4py)
```shift(J, 1)(u)``` is equivalent to ```u["cpc"]```
reference: https://hackmd.io/ueLehFeOR5yyOCtn2Qdr-A

* variant 3: 
Use an offset object (used in icon4py)
```u[JOff(1)]``` is equivalent ```u["cpc"]```
reference: 
https://github.com/C2SM/icon4py/blob/main/atm_dyn_iconam/src/icon4py/atm_dyn_iconam/mo_solve_nonhydro_stencil_04.py

2023-05-24 15:49 UTC, closed without merging