Setup spack
MeteoSwiss-APN/icon_data_processing_incubator pull request #89
Opened 2023-10-16 09:33 UTC by cfkanesan

## Purpose

Setup spack to enable the installation of FDB

## Code changes:

- Added setup spack script.

2023-10-19 12:13 UTC, dominichofer requested changes

2023-10-19 12:13 UTC, dominichofer commented on tools/spack.yaml
> +  specs: [fdb ^eckit@1.20.2 ~mpi ^eccodes@2.25 jp2k=none +fortran ^hdf5 ~mpi]
Why is this environment explicitly requesting the Fortran interface of eccodes?

2023-10-19 12:13 UTC, dominichofer commented on tools/spack.yaml
> +  specs: [fdb ^eckit@1.20.2 ~mpi ^eccodes@2.25 jp2k=none +fortran ^hdf5 ~mpi]
Consider using `~~mpi` [introduced in spack v0.19.0](https://github.com/spack/spack/releases/tag/v0.19.0) like
```
  specs:
  - fdb ~~mpi
  - eckit@1.20.2
  - eccodes@2.25 jp2k=none +fortran
  - hdf5
```
It makes sure all dependencies come without mpi. (I haven't tested this feature yet myself)

2023-10-19 12:13 UTC, dominichofer commented on jenkins/Jenkinsfile
> +        stage('setup spack') {
Consider renaming this, since it's not only setting up spack but also installs the spack environement.

2023-10-19 12:18 UTC, cfkanesan commented on tools/setup_spack.sh
> +spack env activate -p spack-env
cwd is the jenkins workspace and not tools. Do you think it would be better to install the spack environment in the tools dir?

2023-10-19 12:20 UTC, cfkanesan commented on tools/spack.yaml
> +  specs: [fdb ^eckit@1.20.2 ~mpi ^eccodes@2.25 jp2k=none +fortran ^hdf5 ~mpi]
> Why is this environment explicitly requesting the Fortran interface of eccodes?

Copy pasted from Victoria's guide on setting up FDB, maybe it's not necessary but I haven't tried

2023-11-10 09:34 UTC, victoria-cherkas approved these changes
I dont see the need for a setup_spack.sh since its just cloning spack, I would either get rid of it or put all the spack steps in there, eg adding the mirror, doing the install etc. But otherwise looks good

2023-11-10 14:30 UTC, merged